global:
  imagePullPolicy: IfNotPresent
  namespace: ""

images:
  producer: "local/fraud-producer:dev"
  processor: "local/fraud-processor:dev"
  serving: "local/fraud-serving:dev"
  ui: "local/fraud-ui:dev"

service:
  producerPort: 8000
  servingPort: 8000
  uiPort: 8080

storage:
  prefix: v2

kafka:
  enabled: true
  image: "docker.redpanda.com/redpandadata/redpanda:v24.2.14"
  bootstrap: "kafka:9092"
  topic: "transactions"
  topicPartitions: 6
  replicas: 1
  replicationFactor: 1
  storage: "5Gi"
  resources:
    requests:
      cpu: "250m"
      memory: "768Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

minio:
  enabled: true
  distributed: false
  serversPerPool: 4
  poolCount: 1
  image: "quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z"
  mcImage: "quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z"
  endpoint: "http://minio:9000"
  bucket: "fraud"
  storage: "10Gi"
  rootUser: "minioadmin"
  rootPassword: "minioadmin"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

processor:
  replicas: 1
  windowSeconds: "60"
  allowedLatenessSeconds: "120"
  maxFutureSkewSeconds: "300"
  flushEvery: "25"
  highAmount: "800"
  riskThreshold: "0.7"
  velocityThreshold: "10"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "768Mi"

producer:
  replicas: 1
  resources:
    requests:
      cpu: "50m"
      memory: "96Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

serving:
  replicas: 1
  streamPollMs: "1000"
  snapshotCacheMs: "900"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"

ui:
  replicas: 1
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "64Mi"

autoscaling:
  producer:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    cpuUtilization: 70
  serving:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    cpuUtilization: 70
  ui:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 70

keda:
  enabled: false
  processor:
    minReplicaCount: 1
    maxReplicaCount: 6
    lagThreshold: "20"
    consumerGroup: "fraud-processor-v2"
