{{- if .Values.autoscaling.producer.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: producer-hpa
  labels:
    {{- include "fraud-pipeline.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: producer
  minReplicas: {{ .Values.autoscaling.producer.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.producer.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.producer.cpuUtilization }}
{{- end }}
---
{{- if .Values.autoscaling.serving.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: serving-hpa
  labels:
    {{- include "fraud-pipeline.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serving
  minReplicas: {{ .Values.autoscaling.serving.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.serving.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.serving.cpuUtilization }}
{{- end }}
