{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    {{- include "fraud-pipeline.labels" . | nindent 4 }}
spec:
  serviceName: kafka
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: redpanda
          image: {{ .Values.kafka.image | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          command: ["rpk", "redpanda", "start"]
          args:
            - --mode=dev-container
            - --smp=1
            - --memory=512M
            - --reserve-memory=0M
            - --check=false
            - --node-id=0
            - --kafka-addr=PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr=PLAINTEXT://kafka:9092
          ports:
            - containerPort: 9092
              name: kafka
          startupProbe:
            tcpSocket:
              port: kafka
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: kafka
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: kafka
            initialDelaySeconds: 20
            periodSeconds: 15
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.kafka.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    {{- include "fraud-pipeline.labels" . | nindent 4 }}
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
{{- end }}
