apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets
  labels:
    {{- include "fraud-pipeline.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ .Values.minio.rootUser | quote }}
  S3_SECRET_KEY: {{ .Values.minio.rootPassword | quote }}
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
